#!/usr/bin/env python3
"""Generate video 022's short in-character voice lines via ElevenLabs.

Produces ONE short WAV/MP3 per line in assets/voice/022/ (e.g.
01_referee_round_one.mp3). These are short character barks (1-6 words
each), not narration/voice-over — the channel's "no narrator" rule stays
intact (see CLAUDE.md).

SECURITY:
  - ELEVENLABS_API_KEY is read only from .env (via utils.load_env) or the
    real process environment. It is never printed, logged, or written to
    any output file.
  - logs/generation.log only ever records line ids/voice names/output
    paths, never the API key or raw request/response bodies.
  - No real human, celebrity, or copyrighted/impersonated voice is used —
    each character uses an original ElevenLabs voice preset chosen for
    pitch/character, not a clone of any real or fictional copyrighted voice.

Usage:
    python3 scripts/generate_voice_022.py            # dry-run, prints plan, no network call
    python3 scripts/generate_voice_022.py --live      # actually calls ElevenLabs (requires ELEVENLABS_API_KEY)
"""
import argparse
import json
import urllib.error
import urllib.request
from pathlib import Path

from utils import OUTPUTS_DIR, get_logger, load_env

logger = get_logger("generate_voice_022", "generation.log")

VIDEO_ID = "022"
VOICE_DIR = OUTPUTS_DIR.parent / "assets" / "voice" / VIDEO_ID

ELEVENLABS_TTS_URL = "https://api.elevenlabs.io/v1/text-to-speech/{voice_id}"

# Placeholder ElevenLabs voice_ids — replace with real voice IDs chosen/
# designed in the ElevenLabs dashboard (Voice Lab / Voice Design) before
# any --live run. None of these may be a real person's or celebrity's
# cloned voice, or an existing copyrighted character voice.
VOICE_PRESETS = {
    "referee_crumb": {
        "voice_id": "REPLACE_WITH_REFEREE_VOICE_ID",
        "direction": "tiny fast referee, energetic, slightly high-pitched, clear",
        "settings": {"stability": 0.35, "similarity_boost": 0.6, "style": 0.7},
    },
    "wheat_bread": {
        "voice_id": "REPLACE_WITH_WHEAT_BREAD_VOICE_ID",
        "direction": "aggressive, slightly squeaky, angry wheat bread fighter, clear and punchy",
        "settings": {"stability": 0.3, "similarity_boost": 0.6, "style": 0.8},
    },
    "dark_rye": {
        "voice_id": "REPLACE_WITH_DARK_RYE_VOICE_ID",
        "direction": "deeper, cocky, confident dark rye fighter, funny but threatening",
        "settings": {"stability": 0.45, "similarity_boost": 0.65, "style": 0.6},
    },
    "crowd_crumbs": {
        "voice_id": "REPLACE_WITH_CROWD_VOICE_ID",
        "direction": "tiny crowd gasp, layered, chaotic, short",
        "settings": {"stability": 0.2, "similarity_boost": 0.5, "style": 0.9},
    },
}

# Each line: output filename, speaker (-> voice preset), the exact text
# sent to ElevenLabs, and notes. The censored line is sent to the API
# already as "I'll beep you up" — the literal word is never sent to or
# generated by the TTS engine; the beep tone is layered on top afterward
# by the audio-mix step (mix_voice_and_sfx_022.py), not by this script.
VOICE_LINES = [
    {
        "id": "01_referee_round_one",
        "speaker": "referee_crumb",
        "text": "Round one!",
        "scene": 1,
        "start": 0.4,
    },
    {
        "id": "02_wheat_youre_done",
        "speaker": "wheat_bread",
        "text": "You're done, rye.",
        "scene": 3,
        "start": 8.5,
    },
    {
        "id": "03_rye_touch_me",
        "speaker": "dark_rye",
        "text": "Touch me and you're crumbs.",
        "scene": 3,
        "start": 11.0,
    },
    {
        "id": "04_rye_beep_you_up",
        "speaker": "dark_rye",
        "text": "I'll beep you up.",
        "scene": 4,
        "start": 17.2,
        "censor_note": "Sent to TTS as 'beep' placeholder; mix step overlays a short censor "
                        "tone on that word. The uncensored swear is never generated or spoken.",
    },
    {
        "id": "05_crowd_ohhh",
        "speaker": "crowd_crumbs",
        "text": "OHHH!",
        "scene": 4,
        "start": 19.6,
    },
    {
        "id": "06_rye_breakfast_over",
        "speaker": "dark_rye",
        "text": "Breakfast is over.",
        "scene": 5,
        "start": 26.0,
    },
]


def call_elevenlabs(voice_id: str, text: str, settings: dict, api_key: str) -> bytes:
    url = ELEVENLABS_TTS_URL.format(voice_id=voice_id)
    payload = {
        "text": text,
        "model_id": "eleven_multilingual_v2",
        "voice_settings": settings,
    }
    req = urllib.request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "xi-api-key": api_key,
            "Content-Type": "application/json",
            "Accept": "audio/mpeg",
        },
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=60) as resp:
        return resp.read()


def generate_line(line: dict, live: bool, api_key: str | None) -> Path:
    preset = VOICE_PRESETS[line["speaker"]]
    out_path = VOICE_DIR / f"{line['id']}.mp3"

    if not live:
        logger.info(
            "[DRY-RUN] line=%s speaker=%s voice_id=%s text=%r -> %s",
            line["id"], line["speaker"], preset["voice_id"], line["text"], out_path,
        )
        print(
            f"DRY-RUN: would call ElevenLabs voice_id={preset['voice_id']} "
            f"(direction: {preset['direction']}) for line {line['id']!r} "
            f"text={line['text']!r} -> {out_path}"
        )
        return out_path

    if not api_key:
        raise RuntimeError("ELEVENLABS_API_KEY not set in .env — cannot run --live.")
    if preset["voice_id"].startswith("REPLACE_WITH_"):
        raise RuntimeError(
            f"Voice preset for {line['speaker']!r} still has a placeholder voice_id. "
            "Pick/design a real ElevenLabs voice and set it in VOICE_PRESETS before --live."
        )

    audio_bytes = call_elevenlabs(preset["voice_id"], line["text"], preset["settings"], api_key)
    VOICE_DIR.mkdir(parents=True, exist_ok=True)
    out_path.write_bytes(audio_bytes)
    logger.info("Generated line=%s speaker=%s -> %s", line["id"], line["speaker"], out_path)
    print(f"Voice line written: {out_path}")
    return out_path


def generate_all(live: bool) -> list[Path]:
    env = load_env()
    api_key = env.get("ELEVENLABS_API_KEY") or None
    VOICE_DIR.mkdir(parents=True, exist_ok=True)

    paths = []
    for line in VOICE_LINES:
        try:
            paths.append(generate_line(line, live, api_key))
        except urllib.error.HTTPError as exc:
            # Never log response body or headers — they could echo the request including text,
            # but must never include the API key; still avoid dumping raw bodies to be safe.
            logger.error("ElevenLabs call failed for line=%s status=%s", line["id"], exc.code)
            raise
    return paths


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--live", action="store_true")
    args = parser.parse_args()
    generate_all(args.live)


if __name__ == "__main__":
    main()
